-- Drop the unique constraint that forced suffix-mangling of item_code on conflict.
-- Row identity is guaranteed by id (uuid); split parts of the same item are distinguished
-- by split_group_id + split_part. Multiple legitimate parts of the same item_code in the
-- same week (e.g. bundle splits) must be allowed.
ALTER TABLE public.production_schedule
  DROP CONSTRAINT IF EXISTS production_schedule_item_week_unique;

-- Clean up legacy suffixes (_xxxx..xxxxxxxx) that were generated by the old "separate" logic.
UPDATE public.production_inbox
SET item_code = regexp_replace(item_code, '_[a-z0-9]{4,8}$', '', 'i')
WHERE item_code ~ '_[a-z0-9]{4,8}$';

UPDATE public.production_schedule
SET item_code = regexp_replace(item_code, '_[a-z0-9]{4,8}$', '', 'i')
WHERE item_code ~ '_[a-z0-9]{4,8}$' AND is_midflight = false;